# Generated by Django 3.2.6 on 2021-08-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ваша электронная почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='сопроводительное письмо'),
        ),
    ]
